import { V1_TIER_TEXTURE, V2_CURVE, type CurveTable } from '../curve';
import { Difficulties } from '../difficulty';
import {
  CAPACITY_TABLE_MAX_COLS,
  CAPACITY_TABLE_MAX_ROWS,
  SHAPE_CAPACITY_AT_CLAMP,
} from '../shapeCapacityTable';
import {
  V2_MAX_GRID_COLS,
  V2_MAX_GRID_ROWS,
  bagWindowFor,
  bagWindowStats,
  curveWindowMaxTarget,
  placeholderWindowMaxTarget,
  shapeCapacity,
  type BagWindow,
  type WindowMaxTarget,
} from '../shapeBag';
import { SHAPE_CATALOGUE, shapeDefFor } from '../shapeCatalogue';
import { ShapeDef } from '../shapeLibrary';

// V2-FINISH part 3: a warm first v2 pick. A player's first v2 level used to
// rasterize all 26 shapes (capacity) and build every bag window from level 0.
// Now capacity comes from a checked-in table (generated by
// scripts/analysis/capacity-table.ts) and, once the curve has stopped
// changing, a window is computed directly from its ordinal. Neither may
// change a board: the v2 pins in levelGenerator.test.ts and v1Floor.test.ts
// hold, and every window here is compared with the sequential build.

function countTrue(mask: readonly (readonly boolean[])[]): number {
  let n = 0;
  for (const row of mask) for (const cell of row) if (cell) n++;
  return n;
}

function roundHalfToEven(v: number): number {
  const floor = Math.floor(v);
  const diff = v - floor;
  if (diff > 0.5) return floor + 1;
  if (diff < 0.5) return floor;
  return floor % 2 === 0 ? floor : floor + 1;
}

/** Capacity recomputed here, independently of shapeBag.ts: the largest undistorted board at the W3-09 clamp. */
function rasterizedCapacity(shape: ShapeDef): number {
  let rows = 46;
  while (rows > 8 && roundHalfToEven(rows * shape.aspect) > 37) rows--;
  const cols = Math.min(37, Math.max(4, roundHalfToEven(rows * shape.aspect)));
  return countTrue(shape.rasterize(rows, cols));
}

function def(id: string): ShapeDef {
  const shape = shapeDefFor(id);
  if (shape === null) throw new Error(`no ShapeDef for ${id}`);
  return shape;
}

function names(w: BagWindow): string {
  return `${w.ordinal}@${w.start}:${w.order.map((s) => s.name).join(',')}`;
}

describe('V2-FINISH part 3: the capacity table', () => {
  test('it is for the shipped clamp (a clamp change makes this fail: regenerate the table)', () => {
    expect([CAPACITY_TABLE_MAX_ROWS, CAPACITY_TABLE_MAX_COLS]).toEqual([V2_MAX_GRID_ROWS, V2_MAX_GRID_COLS]);
  });

  test('every catalogue shape has an entry, and each equals a fresh rasterization at the clamp', () => {
    expect(Object.keys(SHAPE_CAPACITY_AT_CLAMP).sort()).toEqual([...SHAPE_CATALOGUE].sort());
    for (const id of SHAPE_CATALOGUE) expect([id, SHAPE_CAPACITY_AT_CLAMP[id]]).toEqual([id, rasterizedCapacity(def(id))]);
  });

  test('shapeCapacity serves the table without rasterizing; other caps and unknown shapes still rasterize', () => {
    jest.isolateModules(() => {
      const lib = require('../shapeLibrary') as typeof import('../shapeLibrary');
      const bag = require('../shapeBag') as typeof import('../shapeBag');
      const cat = require('../shapeCatalogue') as typeof import('../shapeCatalogue');
      const spy = jest.spyOn(lib.ShapeDef.prototype, 'rasterize');
      try {
        for (const id of cat.SHAPE_CATALOGUE) bag.shapeCapacity(cat.shapeDefFor(id)!);
        expect(spy).not.toHaveBeenCalled();
        // v1's 46x46 clamp is not in the table: rasterized (and memoized).
        expect(bag.shapeCapacity(cat.shapeDefFor('Square')!, 46, 46)).toBe(2116);
        expect(spy).toHaveBeenCalledTimes(1);
        // A ShapeDef the catalogue does not hold (same name, another instance) is rasterized too.
        const stranger = new lib.ShapeDef('Square', 1, () => true);
        expect(bag.shapeCapacity(stranger)).toBe(37 * 37); // aspect 1 at the clamp: 37 x 37, all inside
        expect(spy).toHaveBeenCalledTimes(2);
      } finally {
        spy.mockRestore();
      }
    });
  });

  test('the table matches shapeCapacity for every catalogue shape', () => {
    for (const id of SHAPE_CATALOGUE) expect([id, shapeCapacity(def(id))]).toEqual([id, SHAPE_CAPACITY_AT_CLAMP[id]]);
  });
});

describe('V2-FINISH part 3: a deep first pick is cheap and deals what the sequential build deals', () => {
  test('a cold first pick at level 20,000 rasterizes nothing and builds only the ramp\'s windows', () => {
    jest.isolateModules(() => {
      const lib = require('../shapeLibrary') as typeof import('../shapeLibrary');
      const bag = require('../shapeBag') as typeof import('../shapeBag');
      const spy = jest.spyOn(lib.ShapeDef.prototype, 'rasterize');
      try {
        bag.pickForLevelV2(20_000);
        expect(spy).not.toHaveBeenCalled();
        const stats = bag.bagWindowStats(bag.v2WindowMaxTarget);
        // S400's ramp ends at index 399; the windows built one by one stop at the first one past it.
        expect(stats.steadyFrom).not.toBeNull();
        expect(stats.built).toBeLessThan(60);
        expect(stats.steadyFrom!.start).toBeGreaterThanOrEqual(V2_CURVE[V2_CURVE.length - 1].levelIndex);
      } finally {
        spy.mockRestore();
      }
    });
  });

  /** The same window-max function without the steady-state registration: the bag builds every window in order. */
  function sequential(wmt: WindowMaxTarget): WindowMaxTarget {
    return (start, end) => wmt(start, end);
  }

  test.each([
    ['fresh S400', curveWindowMaxTarget(V2_CURVE)],
    ['existing player (floored S400)', curveWindowMaxTarget(V2_CURVE, true)],
    ['placeholder bands', placeholderWindowMaxTarget],
  ] as const)('%s: every window 0-30,000 equals the sequential build', (_label, wmt) => {
    const slow = sequential(wmt);
    const bad: string[] = [];
    for (let start = 0; start < 30_000;) {
      const fast = bagWindowFor(start, wmt);
      const ref = bagWindowFor(start, slow);
      if (names(fast) !== names(ref)) bad.push(`${names(fast)} != ${names(ref)}`);
      // Every level of the window resolves to it, via either path.
      if (names(bagWindowFor(start + fast.order.length - 1, wmt)) !== names(ref)) bad.push(`end of ${ref.ordinal}`);
      start = ref.start + ref.order.length;
      if (bad.length > 3) break;
    }
    expect(bad).toEqual([]);
    expect(bagWindowStats(wmt).steadyFrom).not.toBeNull(); // the fast path was the one compared
    expect(bagWindowStats(slow).steadyFrom).toBeNull();
  });

  test('random-order deep lookups equal the sequential build (call order never matters)', () => {
    const wmt = curveWindowMaxTarget(V2_CURVE, true);
    const slow = sequential(wmt);
    let x = 12345;
    for (let k = 0; k < 400; k++) {
      x = (Math.imul(x, 1103515245) + 12345) & 0x7fffffff;
      const i = x % 60_000;
      expect([i, names(bagWindowFor(i, wmt))]).toEqual([i, names(bagWindowFor(i, slow))]);
    }
  });

  test('a curve whose saturated windows are shorter than a tier cycle stays sequential (the shortcut would not be exact)', () => {
    // Only Heart (1033) and Square (1369) hold 1009 cells: windows of two.
    const steep: CurveTable = [
      { levelIndex: 0, baseCells: 88, tierTexture: V1_TIER_TEXTURE },
      { levelIndex: 30, baseCells: 562, tierTexture: V1_TIER_TEXTURE },
    ];
    const wmt = curveWindowMaxTarget(steep);
    const slow = sequential(wmt);
    for (let i = 0; i < 400; i++) expect([i, names(bagWindowFor(i, wmt))]).toEqual([i, names(bagWindowFor(i, slow))]);
    expect(bagWindowStats(wmt).steadyFrom).toBeNull();
  });

  test('a level index far beyond any ramp resolves (O(1): no million windows are built)', () => {
    const wmt = curveWindowMaxTarget(V2_CURVE);
    const w = bagWindowFor(5_000_000, wmt);
    expect(w.start).toBeLessThanOrEqual(5_000_000);
    expect(w.start + w.order.length).toBeGreaterThan(5_000_000);
    expect(bagWindowStats(wmt).built).toBeLessThan(60);
    // Neighbouring windows keep the no-repeat rule across their boundary.
    const next = bagWindowFor(w.start + w.order.length, wmt);
    expect(next.order[0]).not.toBe(w.order[w.order.length - 1]);
    expect(next.ordinal).toBe(w.ordinal + 1);
    expect(Difficulties.cycleLength).toBe(6);
  });
});
