using System.Collections;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace Arrows
{
    /// <summary>
    /// A single tappable arrow on the board. The arrow may span several cells and bend;
    /// it's drawn as one glowing line-art sprite (generated by UIFactory) sized to its
    /// bounding box. A custom raycast filter limits taps to the arrow's actual cells, so
    /// the empty parts of a bent arrow's bounding box (and its glow halo) aren't tappable
    /// and overlapping arrows never steal each other's taps. Forwards taps to BoardManager
    /// and plays its own exit / collision feedback.
    /// </summary>
    [RequireComponent(typeof(RectTransform))]
    public class ArrowTile : MonoBehaviour, IPointerClickHandler, ICanvasRaycastFilter
    {
        public ArrowPath Arrow { get; private set; }

        private BoardManager _board;
        private RectTransform _rt;
        private Image _img;
        private bool _busy;

        public void Init(BoardManager board, ArrowPath arrow, float cellSize)
        {
            _board = board;
            Arrow = arrow;

            _rt = GetComponent<RectTransform>();

            var gen = UIFactory.GenerateArrowPathSprite(arrow.Cells, arrow.HeadDir);
            _rt.sizeDelta = gen.SizeCells * cellSize;
            _rt.localRotation = Quaternion.identity; // the sprite is already oriented

            _img = gameObject.AddComponent<Image>();
            _img.sprite = gen.Sprite;       // white coverage; tinted here
            _img.color = GameManager.Palette.Ink; // black line-art (flashes red when blocked)
            _img.preserveAspect = false;    // sized to the sprite's exact aspect already
            _img.raycastTarget = true;
        }

        /// <summary>
        /// Limits raycasts to the cells the arrow actually occupies. Maps the hit point to
        /// a grid cell within the (padded) bounding box and tests membership.
        /// </summary>
        public bool IsRaycastLocationValid(Vector2 screenPoint, Camera eventCamera)
        {
            if (Arrow == null || _rt == null) return false;
            if (!RectTransformUtility.ScreenPointToLocalPointInRectangle(_rt, screenPoint, eventCamera, out var local))
                return false;

            Rect rect = _rt.rect;
            if (rect.width <= 0f || rect.height <= 0f) return false;

            float pad = UIFactory.ArrowPadCells;
            float u = (local.x - rect.xMin) / rect.width;   // 0 = left, 1 = right
            float v = (local.y - rect.yMin) / rect.height;  // 0 = bottom, 1 = top
            float totalCols = Arrow.ColSpan + 2f * pad;
            float totalRows = Arrow.RowSpan + 2f * pad;

            int relCol = Mathf.FloorToInt(u * totalCols - pad);
            int relRow = Mathf.FloorToInt((1f - v) * totalRows - pad); // grid row 0 is the top
            if (relCol < 0 || relCol >= Arrow.ColSpan || relRow < 0 || relRow >= Arrow.RowSpan)
                return false;

            return Arrow.Contains((Arrow.MinRow + relRow, Arrow.MinCol + relCol));
        }

        public void OnPointerClick(PointerEventData eventData)
        {
            if (_busy || _board == null) return;
            _board.OnArrowTapped(this);
        }

        /// <summary>Horizontal shake + red flash to signal a blocked / illegal move.</summary>
        public IEnumerator PlayShake(float duration = 0.32f, float magnitude = 16f)
        {
            _busy = true;
            Vector2 origin = _rt.anchoredPosition;
            Color red = GameManager.Palette.Heart;
            Color ink = GameManager.Palette.Ink;
            float t = 0f;
            while (t < duration)
            {
                t += Time.deltaTime;
                float k = t / duration;
                float dx = Mathf.Sin(t * 70f) * magnitude * (1f - k);
                _rt.anchoredPosition = origin + new Vector2(dx, 0f);
                if (_img != null) _img.color = Color.Lerp(red, ink, k); // flash red, settle to black
                yield return null;
            }
            _rt.anchoredPosition = origin;
            if (_img != null) _img.color = ink;
            _busy = false;
        }
    }
}
