/**
 * V2-FINISH part 3: generates `src/core/shapeCapacityTable.ts`, generator v2's
 * shape capacities at the shipped clamp, so the first v2 pick in a process
 * does not rasterize every shape.
 *
 * Run:
 *   npx tsx scripts/analysis/capacity-table.ts           # print the module and diff it against the checked-in file
 *   npx tsx scripts/analysis/capacity-table.ts --write   # rewrite src/core/shapeCapacityTable.ts
 *
 * Each capacity is `rasterizedCapacity(shape)` (shapeBag.ts): the shape's
 * cell count on its largest undistorted v2 board, rows = v2MaxRows(aspect)
 * (at most V2_MAX_GRID_ROWS, lowered until the columns fit V2_MAX_GRID_COLS),
 * cols = v2Cols(rows, aspect). `src/core/__tests__/coldPick.test.ts`
 * recomputes every entry by its own rasterization and fails when the clamp
 * or a shape changes, which is the cue to run this with --write.
 *
 * Imports only `src/core`.
 */
import * as fs from 'fs';
import * as path from 'path';
import {
  SHAPE_CATALOGUE,
  V2_MAX_GRID_COLS,
  V2_MAX_GRID_ROWS,
  rasterizedCapacity,
  shapeDefFor,
} from '../../src/core';

const TARGET = path.join(__dirname, '..', '..', 'src', 'core', 'shapeCapacityTable.ts');

function render(): string {
  const rows = SHAPE_CATALOGUE.map((id) => {
    const shape = shapeDefFor(id);
    if (shape === null) throw new Error(`catalogue id '${id}' has no ShapeDef`);
    return `  ${/^[A-Za-z_]\w*$/.test(id) ? id : JSON.stringify(id)}: ${rasterizedCapacity(shape, V2_MAX_GRID_ROWS, V2_MAX_GRID_COLS)},`;
  });
  return [
    '/**',
    ' * GENERATED by `npx tsx scripts/analysis/capacity-table.ts --write` (V2-FINISH part 3). Do not',
    ' * edit by hand: rerun the script, and `src/core/__tests__/coldPick.test.ts` recomputes every',
    ' * entry by rasterization.',
    ' *',
    ' * Generator v2\'s shape capacities at the W3-09 clamp: each catalogue shape\'s cell count on its',
    ' * largest undistorted v2 board (rows = v2MaxRows(aspect), cols = v2Cols(rows, aspect)).',
    ' * `shapeBag.ts` `shapeCapacity` serves these instead of rasterizing all 26 shapes on the first',
    ' * v2 pick of a process. Keyed by catalogue id here; `shapeBag.ts` resolves each id to its',
    ' * ShapeDef instance, so an unknown ShapeDef still rasterizes. Pure core: no imports.',
    ' */',
    '',
    `/** The clamp this table was generated for: V2_MAX_GRID_ROWS x V2_MAX_GRID_COLS. */`,
    `export const CAPACITY_TABLE_MAX_ROWS = ${V2_MAX_GRID_ROWS};`,
    `export const CAPACITY_TABLE_MAX_COLS = ${V2_MAX_GRID_COLS};`,
    '',
    'export const SHAPE_CAPACITY_AT_CLAMP: Readonly<Record<string, number>> = Object.freeze({',
    ...rows,
    '});',
    '',
  ].join('\n');
}

function main(): void {
  const text = render();
  if (process.argv.includes('--write')) {
    fs.writeFileSync(TARGET, text);
    console.log(`wrote ${path.relative(process.cwd(), TARGET)}`);
    return;
  }
  process.stdout.write(text);
  const current = fs.existsSync(TARGET) ? fs.readFileSync(TARGET, 'utf8') : '';
  console.log(current === text ? '// checked-in file: IDENTICAL' : '// checked-in file: DIFFERS (run with --write)');
  if (current !== text) process.exitCode = 1;
}

main();
