/**
 * GENERATED by `npx tsx scripts/analysis/capacity-table.ts --write` (V2-FINISH part 3). Do not
 * edit by hand: rerun the script, and `src/core/__tests__/coldPick.test.ts` recomputes every
 * entry by rasterization.
 *
 * Generator v2's shape capacities at the W3-09 clamp: each catalogue shape's cell count on its
 * largest undistorted v2 board (rows = v2MaxRows(aspect), cols = v2Cols(rows, aspect)).
 * `shapeBag.ts` `shapeCapacity` serves these instead of rasterizing all 26 shapes on the first
 * v2 pick of a process. Keyed by catalogue id here; `shapeBag.ts` resolves each id to its
 * ShapeDef instance, so an unknown ShapeDef still rasterizes. Pure core: no imports.
 */

/** The clamp this table was generated for: V2_MAX_GRID_ROWS x V2_MAX_GRID_COLS. */
export const CAPACITY_TABLE_MAX_ROWS = 46;
export const CAPACITY_TABLE_MAX_COLS = 37;

export const SHAPE_CAPACITY_AT_CLAMP: Readonly<Record<string, number>> = Object.freeze({
  Square: 1369,
  Rectangle: 864,
  Circle: 901,
  Diamond: 613,
  Triangle: 512,
  Plus: 733,
  Hexagon: 809,
  Star: 413,
  Heart: 1033,
  Trophy: 465,
  Crescent: 450,
  Flower: 653,
  Bolt: 202,
  Arrow: 394,
  Crown: 516,
  Hourglass: 688,
  Pentagon: 740,
  Octagon: 869,
  Ring: 696,
  X: 645,
  Butterfly: 674,
  Rocket: 544,
  Pine: 471,
  Cat: 574,
  Mushroom: 609,
  Fish: 507,
  House: 758,
});
